#!/usr/bin/env make
#
# syncfile - sync between two files
#
# Copyright (c) 2003,2023,2025 by Landon Curt Noll.  All Rights Reserved.
#
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby granted,
# provided that the above copyright, this permission notice and text
# this comment, and the disclaimer below appear in all of the following:
#
#       supporting documentation
#       source copies
#       source works derived from this source
#       binaries derived from this source or from derived source
#
# LANDON CURT NOLL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL LANDON CURT NOLL BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
# USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# chongo (Landon Curt Noll) /\oo/\
#
# http://www.isthe.com/chongo/index.html
# https://github.com/lcn2
#
# Share and enjoy!  :-)


#############
# utilities #
#############

CC= cc
CHMOD= chmod
CP= cp
ID= id
INSTALL= install
RM= rm
SHELL= bash

#CFLAGS= -O3 -g3 --pedantic -Wall -Werror
CFLAGS= -O3 -g3 --pedantic -Wall


######################
# target information #
######################

# V=@:  do not echo debug statements (quiet mode)
# V=@   echo debug statements (debug / verbose mode)
#
V=@:
#V=@

PREFIX= /usr/local
DESTDIR= ${PREFIX}/bin

TARGETS= syncfile


######################################
# all - default rule - must be first #
######################################

all: ${TARGETS}
	${V} echo DEBUG =-= $@ start =-=
	${V} echo DEBUG =-= $@ end =-=

have_sendfile.h: have_sendfile.c Makefile
	-@${RM} -f have_sendfile.o have_sendfile have_sendfile.h tmp
	@echo 'forming have_sendfile.h'
	@echo '/*' > have_sendfile.h
	@echo ' * DO NOT EDIT -- generated by the Makefile' >> have_sendfile.h
	@echo ' */' >> have_sendfile.h
	@echo '' >> have_sendfile.h
	@echo '#if !defined(__HAVE_SENDFILE__)' >> have_sendfile.h
	@echo '#define __HAVE_SENDFILE__' >> have_sendfile.h
	@echo '' >> have_sendfile.h
	@echo '/* do we have the sendfile system call? */' >> have_sendfile.h
	-@${CC} ${CFLAGS} have_sendfile.c -o have_sendfile >/dev/null 2>&1;true
	-@${RM} -f tmp
	-@${SHELL} -c "./have_sendfile have_sendfile tmp >/dev/null 2>&1" \
	    >/dev/null 2>&1; true
	-@if ${CMP} -s have_sendfile tmp; then \
	    echo '#define HAVE_SENDFILE /* yes we have the call */'; \
	else \
	    echo '#undef HAVE_SENDFILE /* no we do not have the call */'; \
	fi >> have_sendfile.h
	@echo '' >> have_sendfile.h
	@echo '#endif /* __HAVE_SENDFILE__ */' >> have_sendfile.h
	-@${RM} -f have_sendfile.o have_sendfile tmp
	@echo 'formed have_sendfile.h'

syncfile.o: syncfile.c have_sendfile.h
	${CC} ${CFLAGS} syncfile.c -c

syncfile: syncfile.o
	${CC} ${CFLAGS} syncfile.o -o syncfile


#################################################
# .PHONY list of rules that do not create files #
#################################################

.PHONY: all configure clean clobber install


###################################
# standard Makefile utility rules #
###################################

configure:
	${V} echo DEBUG =-= $@ start =-=
	${V} echo DEBUG =-= $@ end =-=

clean:
	${V} echo DEBUG =-= $@ start =-=
	${RM} -f syncfile.o
	${V} echo DEBUG =-= $@ end =-=

clobber: clean
	${V} echo DEBUG =-= $@ start =-=
	${RM} -f syncfile have_sendfile.h
	${V} echo DEBUG =-= $@ end =-=

install: all
	${V} echo DEBUG =-= $@ start =-=
	@if [[ $$(${ID} -u) != 0 ]]; then echo "ERROR: must be root to make $@" 1>&2; exit 2; fi
	${INSTALL} -d -m 0755 ${DESTDIR}
	${INSTALL} -m 0555 ${TARGETS} ${DESTDIR}
	${V} echo DEBUG =-= $@ end =-=
